### ISSUE TITLE
Morning Standup - Code Review - Nov 26, 2019

### ISSUE THREAD

**Issue by simondebbarma** [sz16900/youtube-homepage#1]
**Daizy** 
-  Good commit messages and Git Flow usage
- Needs a more descriptive README.md [https://medium.com/@meakaakka/a-beginners-guide-to-writing-a-kickass-readme-7ac01da88ab3]
- Use an icon pack like Font Awesome, Open Ionic, Material (+ **Simon**)

**Marian** 
- Try to use flex to display content

**Comment by sz16900** [comment]
**Daizy:**

- Updated README file
- Used Icon8 for icons

**Marian:**

- we decided to use CSS Grid
